# Generated by Django 5.2.3 on 2025-08-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0002_alter_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
