# Generated by Django 5.2.3 on 2025-10-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0003_client_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='qt',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='description',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='acompte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='reste',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='total_payer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nh',
            name='acompte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nh',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nh',
            name='reste',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nh',
            name='total_payer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
