# Generated by Django 5.2.3 on 2025-08-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardex',
            fields=[
                ('id_cardex', models.AutoField(db_column='Id_cardex', primary_key=True, serialize=False)),
                ('id_cons', models.IntegerField(db_column='Id_cons')),
                ('id_traitement', models.IntegerField(db_column='Id_traitement')),
                ('tc', models.CharField(blank=True, db_column='TC', max_length=5, null=True)),
                ('tad', models.CharField(blank=True, db_column='TAD', max_length=5, null=True)),
                ('tas', models.CharField(blank=True, db_column='TAS', max_length=5, null=True)),
                ('fc', models.CharField(blank=True, db_column='FC', max_length=5, null=True)),
                ('fr', models.CharField(blank=True, db_column='FR', max_length=5, null=True)),
                ('sao', models.CharField(blank=True, db_column='SaO', max_length=5, null=True)),
                ('glycemie', models.CharField(blank=True, db_column='Glycemie', max_length=5, null=True)),
                ('date', models.CharField(db_column='Date', max_length=15)),
                ('heure', models.CharField(db_column='Heure', max_length=10)),
                ('observation', models.TextField(blank=True, db_column='Observation', null=True)),
            ],
            options={
                'db_table': 'cardex',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id_consultation', models.AutoField(db_column='Id_consultation', primary_key=True, serialize=False)),
                ('s', models.TextField(blank=True, null=True)),
                ('atcd', models.TextField(blank=True, db_column='ATCD', null=True)),
                ('hma', models.TextField(blank=True, db_column='HMA', null=True)),
                ('ca', models.TextField(blank=True, db_column='CA', null=True)),
                ('ep', models.TextField(blank=True, db_column='EP', null=True)),
                ('a', models.TextField(blank=True, db_column='A', null=True)),
                ('cat', models.TextField(blank=True, db_column='CAT', null=True)),
                ('date', models.TextField(db_column='Date')),
                ('heure', models.CharField(db_column='Heure', max_length=10)),
                ('fac', models.CharField(blank=True, db_column='Fac', max_length=5, null=True)),
            ],
            options={
                'db_table': 'consultation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id_ev', models.AutoField(db_column='Id_ev', primary_key=True, serialize=False)),
                ('s', models.TextField(blank=True, db_column='S', null=True)),
                ('hma', models.TextField(blank=True, db_column='HMA', null=True)),
                ('ca', models.TextField(blank=True, db_column='CA', null=True)),
                ('ep', models.TextField(blank=True, db_column='EP', null=True)),
                ('a', models.TextField(blank=True, db_column='A', null=True)),
                ('date', models.TextField(db_column='Date')),
                ('id_pr', models.IntegerField(db_column='Id_pr')),
                ('id_pa', models.IntegerField(db_column='Id_pa')),
                ('id_con', models.IntegerField(db_column='Id_con')),
            ],
            options={
                'db_table': 'evolution',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Honoraire',
            fields=[
                ('id_h', models.AutoField(primary_key=True, serialize=False)),
                ('prestation', models.CharField(max_length=100)),
                ('qte', models.FloatField(blank=True, null=True)),
                ('pu', models.FloatField()),
                ('pt', models.FloatField()),
                ('categorie', models.CharField(db_column='Categorie', max_length=50)),
                ('id_fac', models.IntegerField(blank=True, db_column='Id_fac', null=True)),
            ],
            options={
                'db_table': 'honoraire',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imagerie',
            fields=[
                ('id_im', models.AutoField(db_column='Id_im', primary_key=True, serialize=False)),
                ('exs', models.TextField(blank=True, db_column='Exs', null=True)),
                ('exd', models.TextField(db_column='Exd')),
                ('rec', models.TextField(blank=True, db_column='Rec', null=True)),
                ('but', models.TextField(blank=True, db_column='But', null=True)),
                ('date', models.CharField(blank=True, db_column='Date', max_length=20, null=True)),
                ('dr_in', models.CharField(blank=True, db_column='Dr_in', max_length=20, null=True)),
                ('interpretation', models.TextField(blank=True, db_column='Interpretation', null=True)),
                ('id_cons', models.IntegerField(db_column='Id_cons')),
                ('id_ev', models.IntegerField(blank=True, db_column='Id_ev', null=True)),
                ('sorte', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'imagerie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Labo',
            fields=[
                ('id_la', models.AutoField(db_column='Id_la', primary_key=True, serialize=False)),
                ('id_ev', models.IntegerField(blank=True, db_column='Id_ev', null=True)),
                ('id_per', models.IntegerField(blank=True, db_column='Id_per', null=True)),
                ('nom_ex', models.CharField(db_column='Nom_ex', max_length=25)),
                ('type_ex', models.CharField(db_column='Type_ex', max_length=25)),
                ('valeur', models.CharField(blank=True, db_column='Valeur', max_length=80, null=True)),
                ('sorte', models.CharField(blank=True, max_length=50, null=True)),
                ('val_normal', models.CharField(blank=True, db_column='Val_normal', max_length=50, null=True)),
            ],
            options={
                'db_table': 'labo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_pa', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(db_column='Nom', max_length=80)),
                ('post_nom', models.CharField(db_column='Post_nom', max_length=80)),
                ('prenom', models.CharField(db_column='Prenom', max_length=80)),
                ('sexe', models.CharField(db_column='Sexe', max_length=80)),
                ('dn', models.CharField(db_column='DN', max_length=80)),
                ('ec', models.CharField(db_column='EC', max_length=80)),
                ('adresse', models.CharField(db_column='Adresse', max_length=80)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=80, null=True)),
                ('profession', models.CharField(blank=True, db_column='Profession', max_length=80, null=True)),
                ('employeur', models.CharField(blank=True, db_column='Employeur', max_length=80, null=True)),
                ('atcd', models.TextField(blank=True, db_column='ATCD', null=True)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id_pr', models.AutoField(db_column='Id_pr', primary_key=True, serialize=False)),
                ('nom', models.CharField(db_column='Nom', max_length=80)),
                ('post_nom', models.CharField(db_column='Post_nom', max_length=80)),
                ('prenom', models.CharField(db_column='Prenom', max_length=80)),
                ('sexe', models.CharField(db_column='Sexe', max_length=80)),
                ('adresse', models.CharField(db_column='Adresse', max_length=80)),
                ('fonction', models.CharField(db_column='Fonction', max_length=80)),
                ('mot_de_passe', models.CharField(db_column='Mot_de_passe', max_length=25)),
                ('cnom', models.CharField(blank=True, db_column='CNOM', max_length=10, null=True)),
            ],
            options={
                'db_table': 'personnel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sv',
            fields=[
                ('id_sv', models.AutoField(db_column='Id_sv', primary_key=True, serialize=False)),
                ('id_pa', models.IntegerField(db_column='Id_pa')),
                ('date', models.CharField(db_column='Date', max_length=25)),
                ('heure', models.CharField(db_column='Heure', max_length=25)),
                ('tc', models.CharField(blank=True, db_column='TC', max_length=10, null=True)),
                ('tas', models.CharField(blank=True, db_column='TAS', max_length=10, null=True)),
                ('tad', models.CharField(blank=True, db_column='TAD', max_length=10, null=True)),
                ('fc', models.CharField(blank=True, db_column='FC', max_length=10, null=True)),
                ('fr', models.CharField(blank=True, db_column='FR', max_length=10, null=True)),
                ('o', models.CharField(blank=True, db_column='O', max_length=80, null=True)),
                ('poid', models.IntegerField(db_column='Poid')),
            ],
            options={
                'db_table': 'sv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id_tr', models.AutoField(db_column='Id_tr', primary_key=True, serialize=False)),
                ('medicament', models.CharField(blank=True, db_column='Medicament', max_length=1000, null=True)),
                ('qt_prise', models.CharField(blank=True, db_column='Qt_prise', max_length=25, null=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=25, null=True)),
                ('mode_emploi', models.CharField(blank=True, max_length=100, null=True)),
                ('prix', models.FloatField(blank=True, db_column='Prix', null=True)),
                ('source', models.CharField(blank=True, db_column='Source', max_length=10, null=True)),
                ('id_ev', models.IntegerField(blank=True, db_column='Id_ev', null=True)),
                ('id_pa', models.IntegerField(blank=True, db_column='Id_pa', null=True)),
                ('id_cons', models.IntegerField(blank=True, db_column='Id_cons', null=True)),
            ],
            options={
                'db_table': 'traitement',
                'managed': False,
            },
        ),
    ]
