# Generated by Django 5.2.3 on 2025-08-07 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cardex',
        ),
        migrations.DeleteModel(
            name='Consultation',
        ),
        migrations.DeleteModel(
            name='Evolution',
        ),
        migrations.DeleteModel(
            name='Honoraire',
        ),
        migrations.DeleteModel(
            name='Imagerie',
        ),
        migrations.DeleteModel(
            name='Labo',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
        migrations.DeleteModel(
            name='Sv',
        ),
        migrations.DeleteModel(
            name='Traitement',
        ),
    ]
